### ISSUE TITLE
Not clear how to integrate build instructions with libscapi

### ISSUE THREAD

**Issue by alex-norton** [cryptobiu/MPC-Benchmark#1]
ex. for MaliciousYaoSingleExecution, If I clone the repo as is and try to "cmake ." and then "make", I get pretty generic errors:

In file included from /home/ar2norto/repos/scapi/MPC-Benchmark/MaliciousYaoSingleExecution/main.cpp:4:0:
/home/ar2norto/repos/scapi/MPC-Benchmark/MaliciousYaoSingleExecution/YaoSEParty.h:8:53: fatal error: libscapi/include/cryptoInfra/Protocol.hpp: No such file or directory
compilation terminated.
CMakeFiles/MaliciousYaoSingleExecution.dir/build.make:62: recipe for target 'CMakeFiles/MaliciousYaoSingleExecution.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/MaliciousYaoSingleExecution.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/MaliciousYaoSingleExecution.dir/all' failed
make[1]: *** [CMakeFiles/MaliciousYaoSingleExecution.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

If I do a libscapi install and then copy the contents of this repo into libscapi/protocols, and update CMakeLists to match my libscapi path, I get:

In file included from /home/ar2norto/repos/scapi/libscapi/protocols/MaliciousYaoSingleExecution/YaoSEParty.h:12:0,
                 from /home/ar2norto/repos/scapi/libscapi/protocols/MaliciousYaoSingleExecution/main.cpp:4:
/home/ar2norto/repos/scapi/libscapi/protocols/MaliciousYaoSingleExecution/../../../libscapi/lib/EMP/emp-m2pc/malicious/malicious.h:3:48: fatal error: /usr/local/include/emp-tool/emp-tool: No such file or directory
compilation terminated.
CMakeFiles/MaliciousYaoSingleExecution.dir/build.make:62: recipe for target 'CMakeFiles/MaliciousYaoSingleExecution.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/MaliciousYaoSingleExecution.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/MaliciousYaoSingleExecution.dir/all' failed
make[1]: *** [CMakeFiles/MaliciousYaoSingleExecution.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Could you include instructions on how to build these given an existing libscapi installation?

**Comment by liorko87** [comment]
Hello @alex-norton, our baseline is that `libscapi` is installed under the home directory.
As you can see in the `CMakeLists.txt` file:

https://github.com/cryptobiu/MPC-Benchmark/blob/ffcbed07aa5927c7c1462405fc6ab149460dcd8c/MaliciousYaoSingleExecution/CMakeLists.txt#L15-L17

If `libscapi` does not installed at the home directory, the protocols won't work
We are working right now for custom installation directory for `libscapi`

**Comment by alex-norton** [comment]
I still have the same error. Here's what I did.

1) Install libscapi in home directory following these instructions: https://libscapi.readthedocs.io/en/latest/install.html#install
2) cd libscapi
3) git clone https://github.com/cryptobiu/MPC-Benchmark
4) cd MPC-Benchmark/MaliciousYaoSingleExecution
5) cmake .
6) make

ar2norto@v1020-wn-249-21:~/libscapi/MPC-Benchmark/MaliciousYaoSingleExecution$ make
Scanning dependencies of target MaliciousYaoSingleExecution
[ 33%] Building CXX object CMakeFiles/MaliciousYaoSingleExecution.dir/main.cpp.o
In file included from /home/ar2norto/libscapi/MPC-Benchmark/MaliciousYaoSingleExecution/YaoSEParty.h:12:0,
                 from /home/ar2norto/libscapi/MPC-Benchmark/MaliciousYaoSingleExecution/main.cpp:4:
/home/ar2norto/libscapi/lib/EMP/emp-m2pc/malicious/malicious.h:3:48: fatal error: /usr/local/include/emp-tool/emp-tool: No such file or directory
compilation terminated.
CMakeFiles/MaliciousYaoSingleExecution.dir/build.make:62: recipe for target 'CMakeFiles/MaliciousYaoSingleExecution.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/MaliciousYaoSingleExecution.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/MaliciousYaoSingleExecution.dir/all' failed
make[1]: *** [CMakeFiles/MaliciousYaoSingleExecution.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by liorko87** [comment]
Did you installed `libscapi` with sudo privileges? EMP requires to be sudo user

**Comment by alex-norton** [comment]
Installing libscapi with sudo priviledges is failing during compile-tests. 

g++: error: ../install/lib/libboost_system.a: No such file or directory
g++: error: ../install/lib/libboost_thread.a: No such file or directory
makefile:99: recipe for target 'compile-tests' failed
make: *** [compile-tests] Error 1

Installing without sudo works fine for the normal libscapi tests, which is bizarre to me. 

Anyway, I've installed EMP separately and can probably just use it directly rather than trying to get this working. I would have liked to get it to build but I don't know what else to try. Feel free to close this issue, though I do think it would be nice to add instructions suggesting where this repo should be put relative to your libscapi installation.

**Comment by alex-norton** [comment]
If I make without sudo then it has libboost_system and libboost_thread.
Here's the whole list:

libblake2.a        libboost_date_time.a   libboost_log_setup.a
libboost_system.a          libcrypto.a        libmiracl.a
libOTExtensionBristol.a  libtests_cryptoTools.a
libboost_atomic.a  libboost_filesystem.a  libboost_regex.a
libboost_thread.a          libcryptoTools.a   libntl.a     libsimpleot.a
libboost_chrono.a  libboost_log.a         libboost_serialization.a
libboost_wserialization.a  liblibOTe_Tests.a  libOTe.a     libssl.a

If I sudo make, then this is what ends up in the folder after the
compilation of compile-tests fails:
libblake2.a  libntl.a  libOTExtensionBristol.a  libsimpleot.a

**Comment by liorko87** [comment]
Hi,

@alex-norton Sorry for the late update.
Please pull the latest version of [libscapi](https://github.com/cryptobiu/libscapi).

**Comment by liorko87** [comment]
I added clear instructions on how to build and install the protocol.
It's compiled and ran successfully on our machines.
