### ISSUE TITLE
issue with make file

### ISSUE THREAD

**Issue by erlichsefi** [cryptobiu/MPC-Benchmark#3]
Hey @moriyaw and @liorko87  nice to meet you virtually : ) 
There is an issue with LowCostConstantRoundMPC, you should update "LowCostConstantRoundMPC/src/Utils.cpp" include from:
`#include "LowCostConstantRoundMPC/include/Utils.hpp"
`to:
`#include "../include/Utils.hpp"`

otherwise, the makefile doesn't find the file.

**Comment by liorko87** [comment]
Hi,

Thanks, I updated it.

Lior
