### ISSUE TITLE
Build fails during integration with libscapi

### ISSUE THREAD

**Issue by mskd12** [cryptobiu/MPC-Benchmark#4]
Hi, 

This seems to be very close to #1. Similar to there, I did the following:

1. Install `libscapi` in my home directory
2. cd libscapi
3. git clone https://github.com/cryptobiu/MPC-Benchmark
4. cd MPC-Benchmark/MaliciousYaoSingleExecution
5. cmake .
6. make

Here's the error
```
In file included from /home/deepak/libscapi/MPC-Benchmark/MaliciousYaoSingleExecution/main.cpp:4:0:
/home/deepak/libscapi/MPC-Benchmark/MaliciousYaoSingleExecution/YaoSEParty.h:10:55: fatal error: libscapi/include/infra/CircuitConverter.hpp: No such file or directory
compilation terminated.
CMakeFiles/MaliciousYaoSingleExecution.dir/build.make:62: recipe for target 'CMakeFiles/MaliciousYaoSingleExecution.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/MaliciousYaoSingleExecution.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/MaliciousYaoSingleExecution.dir/all' failed
make[1]: *** [CMakeFiles/MaliciousYaoSingleExecution.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

Clearly the integration doesn't seem to work. How to fix this?

**Comment by liorko87** [comment]
Hello @mskd12 Please follow the instructions:

1. Pull the latest version of `libscapi`.  
2. Pull the changes from this repository - `MPC-Benchmark`
3. Re-compile the protocol

**Comment by liorko87** [comment]
Please re clone the repository, it's worked on our machines.
