### ISSUE TITLE
Cannot construct GMWparty

### ISSUE THREAD

**Issue by w1001766** [cryptobiu/MPC-Benchmark#8]
I am running the GMW protocol. It can build successfully, but I received this error message:

**key = partyID value = 0
key = circuitFileName value = NigelAes3Parties.txt
key = partiesFileName value = parties.conf
key = inputFileName value = AesInputs0.txt
key = numThreads value = 2
key = internalIterationsNumber value = 5
number of parties = 2
ID = 0
partiesFile = NotFound
in communication
num parties = 2
my id = 0
does not exist**

The "does not exist" was produced after  I put a try/catch around "GMWParty party(argc, argv);". Somehow, the constructor is not working. 

A follow-up question: which module prints out all the info (key = partyID value = 0
, etc.) in the terminal? I couldn't find it :(

**Comment by liorko87** [comment]
GMW is designed for at least 3 parties. 
According to the provide output, you are running 2 parties.

the module that print all the info to the terminal is inside libscapi.  
You can see it [here](https://github.com/cryptobiu/libscapi/blob/master/src/cryptoInfra/Protocol.cpp#L27).

**Comment by w1001766** [comment]
@liorko87 

Thanks, I found the problem.

For a sample command: **./GMW -partyID 0 -circuitFileName NigelAes.txt -partiesFileName parties.conf -inputFileName AesInputs0.txt -numThreads 2 -internalIterationsNumber 1**

Change:  inputFileName to inputFile , partiesFileName to partiesFile. It was a tiny mistake haha.
